"""
Knowledge Pages — Auto-generated documentation from memories

Aggregates memories by session/topic and generates readable Markdown
documents. Inspired by Hindsight's Knowledge Pages.

Usage:
    from vibe_memory.knowledge_pages import KnowledgePageBuilder

    builder = KnowledgePageBuilder(memory)
    page = builder.build_topic("API timeout", atoms)
    # → Markdown string with timeline, key insights, relationships
"""

from typing import Optional
from datetime import datetime
from collections import defaultdict


class KnowledgePageBuilder:
    """Generate Markdown knowledge pages from memory atoms."""

    def __init__(self, memory=None):
        self.memory = memory

    def build_session(
        self,
        session_id: str,
        atoms: list,
        title: Optional[str] = None,
    ) -> str:
        """
        Build a knowledge page for a session.

        Args:
            session_id: Session ID
            atoms: Memory atoms for this session
            title: Page title (default: auto-generated)

        Returns:
            Markdown string
        """
        if not atoms:
            return f"# Session {session_id[:8]}\n\n_No memories recorded._\n"

        title = title or f"Session {session_id[:8]}"
        lines = [
            f"# {title}",
            "",
            f"> Auto-generated by VibeMemory · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"> {len(atoms)} memory atoms",
            "",
            "---",
            "",
            "## Timeline",
            "",
        ]

        # Sort by time
        sorted_atoms = sorted(atoms, key=lambda a: a.created_at if hasattr(a, 'created_at') else datetime.min)

        for i, atom in enumerate(sorted_atoms, 1):
            time_str = atom.created_at.strftime("%H:%M") if hasattr(atom, 'created_at') and atom.created_at else ""
            lines.append(f"### {i}. {time_str} — {atom.summary[:80]}")
            lines.append("")
            lines.append(atom.content)
            lines.append("")
            if atom.tags:
                lines.append(f"Tags: {' '.join('#' + t for t in atom.tags)}")
                lines.append("")

        # Key insights
        lines.append("---")
        lines.append("")
        lines.append("## Key Insights")
        lines.append("")

        insights = [a for a in atoms if "highlight" in (a.tags or []) or "insight" in (a.tags or [])]
        if insights:
            for a in insights:
                lines.append(f"- {a.summary}")
        else:
            lines.append("_No key insights tagged._")

        return "\n".join(lines)

    def build_topic(
        self,
        topic: str,
        atoms: list,
        edges: Optional[list] = None,
    ) -> str:
        """
        Build a knowledge page for a topic across sessions.

        Args:
            topic: Topic name
            atoms: Memory atoms related to this topic
            edges: Optional edges showing relationships

        Returns:
            Markdown string
        """
        lines = [
            f"# {topic}",
            "",
            f"> Auto-generated · {len(atoms)} atoms across sessions",
            "",
            "---",
            "",
            "## Summary",
            "",
            f"This topic spans {len(atoms)} memory atoms.",
            "",
        ]

        # Group by session
        by_session = defaultdict(list)
        for a in atoms:
            sid = a.session_id[:8] if hasattr(a, 'session_id') else "unknown"
            by_session[sid].append(a)

        lines.append("## Sessions")
        lines.append("")
        for sid, session_atoms in sorted(by_session.items()):
            lines.append(f"### Session {sid} ({len(session_atoms)} atoms)")
            lines.append("")
            for a in session_atoms:
                lines.append(f"- **{a.summary[:100]}**")
                if a.tags:
                    lines.append(f"  `{' '.join('#' + t for t in a.tags[:5])}`")
                lines.append("")
            lines.append("")

        # Relationship map
        if edges:
            lines.append("---")
            lines.append("")
            lines.append("## Relationship Map")
            lines.append("")
            lines.append("| From | Relation | To |")
            lines.append("|------|----------|----|")
            for e in edges[:20]:
                from_id = e.from_atom_id[:8] if hasattr(e, 'from_atom_id') else "?"
                to_id = e.to_atom_id[:8] if hasattr(e, 'to_atom_id') else "?"
                label = e.label.value if hasattr(e, 'label') else "?"
                lines.append(f"| {from_id} | {label} | {to_id} |")
            lines.append("")

        return "\n".join(lines)

    def build_project(
        self,
        project_name: str,
        agent_id: Optional[str] = None,
    ) -> str:
        """
        Build a project-level knowledge page.

        Requires self.memory to be set.

        Args:
            project_name: Project name
            agent_id: Agent ID (uses memory's agent_id if not set)

        Returns:
            Markdown string
        """
        if not self.memory:
            return f"# {project_name}\n\n_No memory connected._\n"

        aid = agent_id or self.memory.agent_id
        atoms = self.memory.storage.get_atoms_by_agent(aid, tenant_id=self.memory.tenant_id)
        edges = self.memory.storage.get_all_edges()
        stats = self.memory.stats()

        lines = [
            f"# {project_name} — Knowledge Base",
            "",
            f"> Auto-generated · {stats['total_atoms']} atoms · {stats['total_edges']} edges",
            f"> {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
            "## Project Overview",
            "",
            f"- **Total memories**: {stats['total_atoms']}",
            f"- **Active**: {stats['active_atoms']} · Warm: {stats['warm_atoms']} · Cold: {stats['cold_atoms']}",
            f"- **Relationship edges**: {stats['total_edges']}",
            f"- **Edge types**: {stats.get('edge_labels', {})}",
            "",
        ]

        # By session
        by_session = defaultdict(list)
        for a in atoms:
            sid = a.session_id[:8] if hasattr(a, 'session_id') else "unknown"
            by_session[sid].append(a)

        if by_session:
            lines.append("---")
            lines.append("")
            lines.append("## Sessions")
            lines.append("")
            for sid, session_atoms in sorted(by_session.items(), key=lambda x: len(x[1]), reverse=True):
                lines.append(f"### Session {sid} — {len(session_atoms)} atoms")
                lines.append("")
                for a in session_atoms[:5]:
                    lines.append(f"- {a.summary[:100]}")
                if len(session_atoms) > 5:
                    lines.append(f"  _... and {len(session_atoms) - 5} more_")
                lines.append("")

        # Recent activity
        if atoms:
            lines.append("---")
            lines.append("")
            lines.append("## Recent Activity")
            lines.append("")
            recent = sorted(atoms, key=lambda a: a.created_at if hasattr(a, 'created_at') else datetime.min, reverse=True)[:10]
            for a in recent:
                time_str = a.created_at.strftime("%Y-%m-%d %H:%M") if hasattr(a, 'created_at') and a.created_at else ""
                lines.append(f"- `{time_str}` {a.summary[:100]}")

        return "\n".join(lines)


def build_page(
    memory,
    page_type: str = "project",
    **kwargs,
) -> str:
    """
    Convenience function to build a knowledge page.

    Args:
        memory: VibeMemory instance
        page_type: "project", "session", or "topic"
        **kwargs: Passed to the builder method

    Returns:
        Markdown string
    """
    builder = KnowledgePageBuilder(memory)

    if page_type == "project":
        return builder.build_project(**kwargs)
    elif page_type == "session":
        return builder.build_session(**kwargs)
    elif page_type == "topic":
        return builder.build_topic(**kwargs)
    else:
        raise ValueError(f"Unknown page type: {page_type}")